### ISSUE TITLE
Question about mvitv2 model usage

### ISSUE THREAD

**Issue by K-Hooshanfar** [junwenxiong/diff_sal#2]
I was reviewing your configurations and usage examples in the repository and wanted to confirm if you are using the mvitv2 model as described in the following link: 
[mvitv2 model config](https://github.com/open-mmlab/mmaction2/blob/main/configs/recognition/mvit/README.md)

Could you please clarify if this model was used in your project? Thank you!

**Comment by junwenxiong** [comment]
Yes, we use the mvitv2 config from mmaction2. And the pth link is here [https://download.openmmlab.com/mmaction/v1.0/recognition/mvit/converted/mvit-small-p244_16x4x1_kinetics400-rgb_20221021-9ebaaeed.pth](url).

**Comment by K-Hooshanfar** [comment]
Thanks
