### ISSUE TITLE
pth file miss

### ISSUE THREAD

**Issue by Full-Adder** [junwenxiong/diff_sal#3]
https://github.com/junwenxiong/diff_sal/blob/c9b8070a8fdaafb0bfddb1fb067f1038b42da94c/cfgs/audio_visual.py#L31

Nice work! I am trying to run your code but where can i get this .pth file?

**Comment by Full-Adder** [comment]
add also 'vggish': 'data/pretrained_models/vggish.pth',

**Comment by Full-Adder** [comment]
when i ues python=3.10, in  datasets/spatial_transforms.py raise  module ‘collections‘ has no attribute ‘Iterable‘, i fix these bug using  collections.abc.Iterable

**Comment by junwenxiong** [comment]
Sorry for late reply. The pth link is here [https://download.openmmlab.com/mmaction/v1.0/recognition/mvit/converted/mvit-small-p244_16x4x1_kinetics400-rgb_20221021-9ebaaeed.pth](url).  And the vggish is from [https://github.com/harritaylor/torchvggish](torchvggish).
